'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class MyResources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("标准文件形式检查助手.MyResources", GetType(MyResources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property AbbChkBtn_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AbbChkBtn.Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property AboutBtn_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AboutBtn.Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property AIwriting_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AIwriting.Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property ApplyStyleBtn_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ApplyStyleBtn.Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property BeautifyTblBtn_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BeautifyTblBtn.Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property BibRefChkBtn_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BibRefChkBtn.Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property BibValidBtn_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BibValidBtn.Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property BignumMdfBtn_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BignumMdfBtn.Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property CoverChkBtn_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CoverChkBtn.Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property DonateBtn_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DonateBtn.Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property ForewordChkBtn_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ForewordChkBtn.Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property ListChkBtn_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ListChkBtn.Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MergeTblBtn_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MergeTblBtn.Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property runBtn_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("runBtn.Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property SearchStdBtn_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SearchStdBtn.Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property SettingBtn_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SettingBtn.Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property SplitTblBtn_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SplitTblBtn.Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property StructureChkBtn_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StructureChkBtn.Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property TermsChkBtn_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TermsChkBtn.Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property UnitMdfBtn_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UnitMdfBtn.Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property VarFontMdfBtn_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VarFontMdfBtn.Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
